version: "3.5"

services:
 leggo-content:
   image: leggo/leggo-content
   build:
     context: ./
     dockerfile: ./Dockerfile
   volumes:
     - leggo_content_data:/leggo-content/leggo_content_data

volumes:
  leggo_content_data:
    external:
      name: leggo_content_data